version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: ehs_enforcement_postgres
    environment:
      POSTGRES_DB: ehs_enforcement_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"  # Use port 5434 to avoid conflict
    volumes:
      - ehs_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  ehs_postgres_data: