defmodule EhsEnforcement.Repo.Migrations.RenameAgencyActiveToEnabled do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:agencies), :active, to: :enabled
  end

  def down do
    rename table(:agencies), :enabled, to: :active
  end
end
