defmodule EhsEnforcement.Repo.Migrations.AddNormalizedNameToOffenders do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:offenders) do
      add :normalized_name, :text
    end

    # Populate normalized_name for existing records
    execute """
    UPDATE offenders 
    SET normalized_name = LOWER(
      REGEXP_REPLACE(
        REGEXP_REPLACE(
          REGEXP_REPLACE(
            TRIM(name),
            '\\s+(limited|ltd\\.?)$', ' limited', 'i'
          ),
          '\\s+(plc|p\\.l\\.c\\.?)$', ' plc', 'i'
        ),
        '\\s+', ' ', 'g'
      )
    )
    """

    drop_if_exists unique_index(:offenders, [:name, :postcode],
                     name: "offenders_unique_name_postcode_index"
                   )

    create unique_index(:offenders, [:normalized_name, :postcode],
             name: "offenders_unique_name_postcode_index"
           )
  end

  def down do
    drop_if_exists unique_index(:offenders, [:normalized_name, :postcode],
                     name: "offenders_unique_name_postcode_index"
                   )

    create unique_index(:offenders, [:name, :postcode],
             name: "offenders_unique_name_postcode_index"
           )

    alter table(:offenders) do
      remove :normalized_name
    end
  end
end
